Main:
    HttpPort: 8088
    HttpsOn: false
    Domain: "ohko.cn"
    HttpsPort: 443
    PubDir: "static"
    ViewDir: "view/default"
    Youdb: "data/mydata.db"
    CookieSecure: false
    CookieHttpOnly: true
    OldSiteDomain: ""
    TLSCrtFile: ""
    TLSKeyFile: ""
Site:
    Name: "金茂光明城市"
    Desc: "拒绝无为无治，重建光明城市"
    AdminEmail: ""
    MainDomain: "https://ohko.cn"
    MainNodeIds: "1,2,3,4,5,6,7,8,9,10"
    TimeZone: 8
    HomeShowNum: 20
    PageShowNum: 20
    TagShowNum: 20
    CategoryShowNum: 20
    TitleMaxLen: 180
    ContentMaxLen: 9000
    PostInterval: 60
    CommentListNum: 10
    CommentInterval: 20
    Authorized: false
    RegReview: false
    CloseReg: false
    AutoDataBackup: false
    AutoGetTag: true
    GetTagApi: "http://youbbs.sinaapp.com/fencigoapi.php"
    QQClientID: 0
    QQClientSecret: ""
    WeiboClientID: 0
    WeiboClientSecret: ""
    UploadSuffix: ""
    UploadImgOnly: false
    UploadImgResize: false
    UploadMaxSize: 50
    QiniuAccessKey: ""
    QiniuSecretKey: ""
    QiniuDomain: ""
    QiniuBucket: ""
    UpyunDomain: ""
    UpyunBucket: ""
    UpyunUser: ""
    UpyunPw: ""
